<a href="https://colab.research.google.com/github/Sumanasri02/ai-ml-learning-journey/blob/main/02_Python_for_ML/01_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics for Machine Learning

## Overview
NumPy is the core Python library for numerical computing.
It is heavily used in Machine Learning for handling arrays, matrices,
and mathematical operations efficiently.


In [6]:
import numpy as np

## Why NumPy?
- Faster than Python lists
- Supports vectorized operations
- Backbone of Pandas, Scikit-learn, TensorFlow


In [7]:
# Creating NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array:", arr1)
print("2D array: \n", arr2)

1D array: [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


## Array Properties
- Shape
- Size
- Data type


In [8]:
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)


Shape: (2, 3)
Size: 6
Data type: int64


## Basic Operations
NumPy supports element-wise operations.


In [9]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


## Statistical Functions
NumPy provides fast statistical operations.


In [10]:
data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0


## Reshaping Arrays
Reshaping is common when preparing data for ML models.


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped)


Reshaped Array:
 [[1 2 3]
 [4 5 6]]


## Key Takeaways
- NumPy arrays are faster than Python lists
- Supports vectorized mathematical operations
- Essential for data preprocessing in ML
