<a href="https://colab.research.google.com/github/Sumanasri02/ai-ml-learning-journey/blob/main/01_Math_Foundations/01_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear algebra for Machine Learning

##overview
Linear Algebra is the backbone of mant ML algorithms.
this notebook covers vectors, matrices, and basic operations in python using Numpy.


In [1]:
import numpy as np


## Vectors
A vector is an array of numbers representing magnitude and direction.

In [2]:
# Example vector
v = np.array([2, 3, 4])
u = np.array([1, 0, 2])

print("vector v:", v)
print("v + u=", v + u)
print("Dot Product v.u =", np.dot(v, u))

vector v: [2 3 4]
v + u= [3 3 6]
Dot Product v.u = 10


## Matrices
A matrix is a 2D array of numbers used to represent data or transformations.

In [3]:
# Example matrices
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B:\n", A + B)
print("A dot B:\n", np.dot(A, B))
print("Transpose of A:\n", A.T)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B:
 [[ 6  8]
 [10 12]]
A dot B:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


## Key Takeaways
- Vectors represent points or directions
- Dot product measures similarity between vectors
- Matrices store tabular data or transformations
- Matrix multiplication is fundamental in ML computations.